/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.jami.daemon;

public class StringMap extends java.util.AbstractMap<String, String> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StringMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JamiServiceJNI.delete_StringMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static StringMap toSwig(java.util.Map<String,String> in) {
    StringMap n = new StringMap();
    for (java.util.Map.Entry<String, String> entry : in.entrySet()) {
      if (entry.getValue() != null) {
        n.put(entry.getKey(), entry.getValue());
      }
    }
    return n;
  }

  public java.util.HashMap<String,String> toNative() {
    java.util.HashMap<String,String> out = new java.util.HashMap<>((int)size());
    for (Entry<String, String> e : entrySet())
        out.put(e.getKey(), e.getValue());
    return out;
  }

  public java.util.HashMap<String,String> toNativeFromUtf8() {
      java.util.HashMap<String,String> out = new java.util.HashMap<>((int)size());
      StringVect keys = keys();
      for (String s : keys) {
        out.put(s, getRaw(s).toJavaString());
      }
      return out;
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof String)) {
      return false;
    }

    return containsImpl((String)key);
  }

  public String get(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public String put(String key, String value) {
    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      String oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public String remove(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      String oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<String, String>> entrySet() {
    java.util.Set<Entry<String, String>> setToReturn =
        new java.util.HashSet<Entry<String, String>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<String, String>() {
        private Iterator iterator;

        private Entry<String, String> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public String getKey() {
          return iterator.getKey();
        }

        public String getValue() {
          return iterator.getValue();
        }

        public String setValue(String newValue) {
          String oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public StringMap() {
    this(JamiServiceJNI.new_StringMap__SWIG_0(), true);
  }

  public StringMap(StringMap other) {
    this(JamiServiceJNI.new_StringMap__SWIG_1(StringMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          JamiServiceJNI.delete_StringMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private StringMap.Iterator getNextUnchecked() {
      return new StringMap.Iterator(JamiServiceJNI.StringMap_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(StringMap.Iterator other) {
      return JamiServiceJNI.StringMap_Iterator_isNot(swigCPtr, this, StringMap.Iterator.getCPtr(other), other);
    }
  
    private String getKey() {
      return JamiServiceJNI.StringMap_Iterator_getKey(swigCPtr, this);
    }
  
    private String getValue() {
      return JamiServiceJNI.StringMap_Iterator_getValue(swigCPtr, this);
    }
  
    private void setValue(String newValue) {
      JamiServiceJNI.StringMap_Iterator_setValue(swigCPtr, this, newValue);
    }
  
  }

  public boolean isEmpty() {
    return JamiServiceJNI.StringMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    JamiServiceJNI.StringMap_clear(swigCPtr, this);
  }

  private StringMap.Iterator find(String key) {
    return new StringMap.Iterator(JamiServiceJNI.StringMap_find(swigCPtr, this, key), true);
  }

  private StringMap.Iterator begin() {
    return new StringMap.Iterator(JamiServiceJNI.StringMap_begin(swigCPtr, this), true);
  }

  private StringMap.Iterator end() {
    return new StringMap.Iterator(JamiServiceJNI.StringMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return JamiServiceJNI.StringMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(String key) {
    return JamiServiceJNI.StringMap_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(String key, String value) {
    JamiServiceJNI.StringMap_putUnchecked(swigCPtr, this, key, value);
  }

  private void removeUnchecked(StringMap.Iterator itr) {
    JamiServiceJNI.StringMap_removeUnchecked(swigCPtr, this, StringMap.Iterator.getCPtr(itr), itr);
  }

  public StringVect keys() {
    return new StringVect(JamiServiceJNI.StringMap_keys(swigCPtr, this), true);
  }

  public void setRaw(String key, Blob value) {
    JamiServiceJNI.StringMap_setRaw(swigCPtr, this, key, Blob.getCPtr(value), value);
  }

  public Blob getRaw(String key) {
    return new Blob(JamiServiceJNI.StringMap_getRaw(swigCPtr, this, key), true);
  }

}
