/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.savoirfairelinux.sflphone.service;

public class Callback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Callback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Callback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SFLPhoneserviceJNI.delete_Callback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    SFLPhoneserviceJNI.Callback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    SFLPhoneserviceJNI.Callback_change_ownership(this, swigCPtr, true);
  }

  public void on_new_call_created(String arg1, String arg2, String arg3) {
    if (getClass() == Callback.class) SFLPhoneserviceJNI.Callback_on_new_call_created(swigCPtr, this, arg1, arg2, arg3); else SFLPhoneserviceJNI.Callback_on_new_call_createdSwigExplicitCallback(swigCPtr, this, arg1, arg2, arg3);
  }

  public void on_call_state_changed(String arg1, String arg2) {
    if (getClass() == Callback.class) SFLPhoneserviceJNI.Callback_on_call_state_changed(swigCPtr, this, arg1, arg2); else SFLPhoneserviceJNI.Callback_on_call_state_changedSwigExplicitCallback(swigCPtr, this, arg1, arg2);
  }

  public void on_incoming_call(String arg1, String arg2, String arg3) {
    if (getClass() == Callback.class) SFLPhoneserviceJNI.Callback_on_incoming_call(swigCPtr, this, arg1, arg2, arg3); else SFLPhoneserviceJNI.Callback_on_incoming_callSwigExplicitCallback(swigCPtr, this, arg1, arg2, arg3);
  }

  public void on_transfer_state_changed(String arg1) {
    if (getClass() == Callback.class) SFLPhoneserviceJNI.Callback_on_transfer_state_changed(swigCPtr, this, arg1); else SFLPhoneserviceJNI.Callback_on_transfer_state_changedSwigExplicitCallback(swigCPtr, this, arg1);
  }

  public void on_conference_created(String arg1) {
    if (getClass() == Callback.class) SFLPhoneserviceJNI.Callback_on_conference_created(swigCPtr, this, arg1); else SFLPhoneserviceJNI.Callback_on_conference_createdSwigExplicitCallback(swigCPtr, this, arg1);
  }

  public void on_conference_removed(String arg1) {
    if (getClass() == Callback.class) SFLPhoneserviceJNI.Callback_on_conference_removed(swigCPtr, this, arg1); else SFLPhoneserviceJNI.Callback_on_conference_removedSwigExplicitCallback(swigCPtr, this, arg1);
  }

  public void on_conference_state_changed(String arg1, String arg2) {
    if (getClass() == Callback.class) SFLPhoneserviceJNI.Callback_on_conference_state_changed(swigCPtr, this, arg1, arg2); else SFLPhoneserviceJNI.Callback_on_conference_state_changedSwigExplicitCallback(swigCPtr, this, arg1, arg2);
  }

  public void on_incoming_message(String ID, String from, String msg) {
    if (getClass() == Callback.class) SFLPhoneserviceJNI.Callback_on_incoming_message(swigCPtr, this, ID, from, msg); else SFLPhoneserviceJNI.Callback_on_incoming_messageSwigExplicitCallback(swigCPtr, this, ID, from, msg);
  }

  public void on_record_playback_filepath(String id, String filename) {
    if (getClass() == Callback.class) SFLPhoneserviceJNI.Callback_on_record_playback_filepath(swigCPtr, this, id, filename); else SFLPhoneserviceJNI.Callback_on_record_playback_filepathSwigExplicitCallback(swigCPtr, this, id, filename);
  }

  public Callback() {
    this(SFLPhoneserviceJNI.new_Callback(), true);
    SFLPhoneserviceJNI.Callback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
