/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.savoirfairelinux.sflphone.service;

public class ConfigurationCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ConfigurationCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConfigurationCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SFLPhoneserviceJNI.delete_ConfigurationCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    SFLPhoneserviceJNI.ConfigurationCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    SFLPhoneserviceJNI.ConfigurationCallback_change_ownership(this, swigCPtr, true);
  }

  public void on_accounts_changed() {
    if (getClass() == ConfigurationCallback.class) SFLPhoneserviceJNI.ConfigurationCallback_on_accounts_changed(swigCPtr, this); else SFLPhoneserviceJNI.ConfigurationCallback_on_accounts_changedSwigExplicitConfigurationCallback(swigCPtr, this);
  }

  public void on_account_state_changed(String accoundID, int state) {
    if (getClass() == ConfigurationCallback.class) SFLPhoneserviceJNI.ConfigurationCallback_on_account_state_changed(swigCPtr, this, accoundID, state); else SFLPhoneserviceJNI.ConfigurationCallback_on_account_state_changedSwigExplicitConfigurationCallback(swigCPtr, this, accoundID, state);
  }

  public void on_account_state_changed_with_code(String accoundID, String state, int code) {
    if (getClass() == ConfigurationCallback.class) SFLPhoneserviceJNI.ConfigurationCallback_on_account_state_changed_with_code(swigCPtr, this, accoundID, state, code); else SFLPhoneserviceJNI.ConfigurationCallback_on_account_state_changed_with_codeSwigExplicitConfigurationCallback(swigCPtr, this, accoundID, state, code);
  }

  public ConfigurationCallback() {
    this(SFLPhoneserviceJNI.new_ConfigurationCallback(), true);
    SFLPhoneserviceJNI.ConfigurationCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
