.\" zerofill - clear unused disk space and blank devices.
.\" Copyright (c) 2010 David Sugar <dyfet@gnutelephony.org>
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian GNU/Linux.
.\"
.TH zerofill "1" "January 2010" "GNU uCommon" "GNU Telephony"
.SH NAME
zerofill \- clear unused disk space and blank devices.
.SH SYNOPSIS
.B zerofill
.RI [ options ]
.RI [ devices ]
.I ...
.br
.SH DESCRIPTION
This command is a relative of nullfile.  Like nullfile, it can be used
to write all unused disk space with '0', thereby making file systems that
are stored on virtual machines easier to pack.  In addition, zerofill can
fill unused disk space with random data before zeroing, which can be useful
to remove forensic trace of deleted files.  Finally, zerofile can be told
to operate on and zero (erase) complete disk devices.
.SH OPTIONS
.TP
.BI \-\-random= count
Number of passes to use writing random data before wiping data.
.TP
.B \-\-help
Outputs help screen for the user.
.SH AUTHOR
.B zerofill
was written by David Sugar <dyfet@gnutelephony.org>.
.SH "REPORTING BUGS"
Report bugs to bug-commoncpp@gnu.org.
.SH COPYRIGHT
Copyright \(co 2010 David Sugar, Tycho Softworks.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.


