/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.jami.daemon;

public class MessageVect extends java.util.AbstractList<Message> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MessageVect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MessageVect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JamiServiceJNI.delete_MessageVect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MessageVect(Message[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Message element : initialElements) {
      add(element);
    }
  }

  public MessageVect(Iterable<Message> initialElements) {
    this();
    for (Message element : initialElements) {
      add(element);
    }
  }

  public Message get(int index) {
    return doGet(index);
  }

  public Message set(int index, Message e) {
    return doSet(index, e);
  }

  public boolean add(Message e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Message e) {
    modCount++;
    doAdd(index, e);
  }

  public Message remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public MessageVect() {
    this(JamiServiceJNI.new_MessageVect__SWIG_0(), true);
  }

  public MessageVect(MessageVect other) {
    this(JamiServiceJNI.new_MessageVect__SWIG_1(MessageVect.getCPtr(other), other), true);
  }

  public long capacity() {
    return JamiServiceJNI.MessageVect_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    JamiServiceJNI.MessageVect_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return JamiServiceJNI.MessageVect_isEmpty(swigCPtr, this);
  }

  public void clear() {
    JamiServiceJNI.MessageVect_clear(swigCPtr, this);
  }

  public MessageVect(int count, Message value) {
    this(JamiServiceJNI.new_MessageVect__SWIG_2(count, Message.getCPtr(value), value), true);
  }

  private int doSize() {
    return JamiServiceJNI.MessageVect_doSize(swigCPtr, this);
  }

  private void doAdd(Message x) {
    JamiServiceJNI.MessageVect_doAdd__SWIG_0(swigCPtr, this, Message.getCPtr(x), x);
  }

  private void doAdd(int index, Message x) {
    JamiServiceJNI.MessageVect_doAdd__SWIG_1(swigCPtr, this, index, Message.getCPtr(x), x);
  }

  private Message doRemove(int index) {
    return new Message(JamiServiceJNI.MessageVect_doRemove(swigCPtr, this, index), true);
  }

  private Message doGet(int index) {
    return new Message(JamiServiceJNI.MessageVect_doGet(swigCPtr, this, index), false);
  }

  private Message doSet(int index, Message val) {
    return new Message(JamiServiceJNI.MessageVect_doSet(swigCPtr, this, index, Message.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    JamiServiceJNI.MessageVect_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
