/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cx.ring.daemon;

public class ConfigurationCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConfigurationCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConfigurationCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RingserviceJNI.delete_ConfigurationCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    RingserviceJNI.ConfigurationCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    RingserviceJNI.ConfigurationCallback_change_ownership(this, swigCPtr, true);
  }

  public void volumeChanged(String device, int value) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_volumeChanged(swigCPtr, this, device, value); else RingserviceJNI.ConfigurationCallback_volumeChangedSwigExplicitConfigurationCallback(swigCPtr, this, device, value);
  }

  public void accountsChanged() {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_accountsChanged(swigCPtr, this); else RingserviceJNI.ConfigurationCallback_accountsChangedSwigExplicitConfigurationCallback(swigCPtr, this);
  }

  public void historyChanged() {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_historyChanged(swigCPtr, this); else RingserviceJNI.ConfigurationCallback_historyChangedSwigExplicitConfigurationCallback(swigCPtr, this);
  }

  public void stunStatusFailure(String account_id) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_stunStatusFailure(swigCPtr, this, account_id); else RingserviceJNI.ConfigurationCallback_stunStatusFailureSwigExplicitConfigurationCallback(swigCPtr, this, account_id);
  }

  public void accountDetailsChanged(String account_id, StringMap details) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_accountDetailsChanged(swigCPtr, this, account_id, StringMap.getCPtr(details), details); else RingserviceJNI.ConfigurationCallback_accountDetailsChangedSwigExplicitConfigurationCallback(swigCPtr, this, account_id, StringMap.getCPtr(details), details);
  }

  public void profileReceived(String arg0, String arg1, String arg2) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_profileReceived(swigCPtr, this, arg0, arg1, arg2); else RingserviceJNI.ConfigurationCallback_profileReceivedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1, arg2);
  }

  public void registrationStateChanged(String account_id, String state, int code, String detail_str) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_registrationStateChanged(swigCPtr, this, account_id, state, code, detail_str); else RingserviceJNI.ConfigurationCallback_registrationStateChangedSwigExplicitConfigurationCallback(swigCPtr, this, account_id, state, code, detail_str);
  }

  public void volatileAccountDetailsChanged(String account_id, StringMap details) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_volatileAccountDetailsChanged(swigCPtr, this, account_id, StringMap.getCPtr(details), details); else RingserviceJNI.ConfigurationCallback_volatileAccountDetailsChangedSwigExplicitConfigurationCallback(swigCPtr, this, account_id, StringMap.getCPtr(details), details);
  }

  public void incomingAccountMessage(String arg0, String arg1, String arg2, StringMap arg3) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_incomingAccountMessage(swigCPtr, this, arg0, arg1, arg2, StringMap.getCPtr(arg3), arg3); else RingserviceJNI.ConfigurationCallback_incomingAccountMessageSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1, arg2, StringMap.getCPtr(arg3), arg3);
  }

  public void accountMessageStatusChanged(String arg0, long arg1, String arg2, int arg3) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_accountMessageStatusChanged(swigCPtr, this, arg0, arg1, arg2, arg3); else RingserviceJNI.ConfigurationCallback_accountMessageStatusChangedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1, arg2, arg3);
  }

  public void composingStatusChanged(String arg0, String arg1, int arg2) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_composingStatusChanged(swigCPtr, this, arg0, arg1, arg2); else RingserviceJNI.ConfigurationCallback_composingStatusChangedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1, arg2);
  }

  public void knownDevicesChanged(String arg0, StringMap arg1) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_knownDevicesChanged(swigCPtr, this, arg0, StringMap.getCPtr(arg1), arg1); else RingserviceJNI.ConfigurationCallback_knownDevicesChangedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, StringMap.getCPtr(arg1), arg1);
  }

  public void exportOnRingEnded(String arg0, int arg1, String arg2) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_exportOnRingEnded(swigCPtr, this, arg0, arg1, arg2); else RingserviceJNI.ConfigurationCallback_exportOnRingEndedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1, arg2);
  }

  public void incomingTrustRequest(String arg0, String arg1, Blob arg2, long received) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_incomingTrustRequest(swigCPtr, this, arg0, arg1, Blob.getCPtr(arg2), arg2, received); else RingserviceJNI.ConfigurationCallback_incomingTrustRequestSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1, Blob.getCPtr(arg2), arg2, received);
  }

  public void contactAdded(String arg0, String arg1, boolean confirmed) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_contactAdded(swigCPtr, this, arg0, arg1, confirmed); else RingserviceJNI.ConfigurationCallback_contactAddedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1, confirmed);
  }

  public void contactRemoved(String arg0, String arg1, boolean banned) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_contactRemoved(swigCPtr, this, arg0, arg1, banned); else RingserviceJNI.ConfigurationCallback_contactRemovedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1, banned);
  }

  public void certificatePinned(String arg0) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_certificatePinned(swigCPtr, this, arg0); else RingserviceJNI.ConfigurationCallback_certificatePinnedSwigExplicitConfigurationCallback(swigCPtr, this, arg0);
  }

  public void certificatePathPinned(String arg0, StringVect arg1) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_certificatePathPinned(swigCPtr, this, arg0, StringVect.getCPtr(arg1), arg1); else RingserviceJNI.ConfigurationCallback_certificatePathPinnedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, StringVect.getCPtr(arg1), arg1);
  }

  public void certificateExpired(String arg0) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_certificateExpired(swigCPtr, this, arg0); else RingserviceJNI.ConfigurationCallback_certificateExpiredSwigExplicitConfigurationCallback(swigCPtr, this, arg0);
  }

  public void certificateStateChanged(String arg0, String arg1, String arg2) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_certificateStateChanged(swigCPtr, this, arg0, arg1, arg2); else RingserviceJNI.ConfigurationCallback_certificateStateChangedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1, arg2);
  }

  public void errorAlert(int alert) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_errorAlert(swigCPtr, this, alert); else RingserviceJNI.ConfigurationCallback_errorAlertSwigExplicitConfigurationCallback(swigCPtr, this, alert);
  }

  public void getHardwareAudioFormat(IntVect arg0) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_getHardwareAudioFormat(swigCPtr, this, IntVect.getCPtr(arg0), arg0); else RingserviceJNI.ConfigurationCallback_getHardwareAudioFormatSwigExplicitConfigurationCallback(swigCPtr, this, IntVect.getCPtr(arg0), arg0);
  }

  public void getAppDataPath(String arg0, StringVect arg1) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_getAppDataPath(swigCPtr, this, arg0, StringVect.getCPtr(arg1), arg1); else RingserviceJNI.ConfigurationCallback_getAppDataPathSwigExplicitConfigurationCallback(swigCPtr, this, arg0, StringVect.getCPtr(arg1), arg1);
  }

  public void getDeviceName(StringVect arg0) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_getDeviceName(swigCPtr, this, StringVect.getCPtr(arg0), arg0); else RingserviceJNI.ConfigurationCallback_getDeviceNameSwigExplicitConfigurationCallback(swigCPtr, this, StringVect.getCPtr(arg0), arg0);
  }

  public void nameRegistrationEnded(String arg0, int state, String arg2) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_nameRegistrationEnded(swigCPtr, this, arg0, state, arg2); else RingserviceJNI.ConfigurationCallback_nameRegistrationEndedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, state, arg2);
  }

  public void registeredNameFound(String arg0, int state, String arg2, String arg3) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_registeredNameFound(swigCPtr, this, arg0, state, arg2, arg3); else RingserviceJNI.ConfigurationCallback_registeredNameFoundSwigExplicitConfigurationCallback(swigCPtr, this, arg0, state, arg2, arg3);
  }

  public void userSearchEnded(String arg0, int state, String arg2, VectMap arg3) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_userSearchEnded(swigCPtr, this, arg0, state, arg2, VectMap.getCPtr(arg3), arg3); else RingserviceJNI.ConfigurationCallback_userSearchEndedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, state, arg2, VectMap.getCPtr(arg3), arg3);
  }

  public void migrationEnded(String arg0, String arg1) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_migrationEnded(swigCPtr, this, arg0, arg1); else RingserviceJNI.ConfigurationCallback_migrationEndedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1);
  }

  public void deviceRevocationEnded(String arg0, String arg1, int arg2) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_deviceRevocationEnded(swigCPtr, this, arg0, arg1, arg2); else RingserviceJNI.ConfigurationCallback_deviceRevocationEndedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1, arg2);
  }

  public void accountProfileReceived(String arg0, String arg1, String arg2) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_accountProfileReceived(swigCPtr, this, arg0, arg1, arg2); else RingserviceJNI.ConfigurationCallback_accountProfileReceivedSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1, arg2);
  }

  public void hardwareDecodingChanged(boolean arg0) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_hardwareDecodingChanged(swigCPtr, this, arg0); else RingserviceJNI.ConfigurationCallback_hardwareDecodingChangedSwigExplicitConfigurationCallback(swigCPtr, this, arg0);
  }

  public void hardwareEncodingChanged(boolean arg0) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_hardwareEncodingChanged(swigCPtr, this, arg0); else RingserviceJNI.ConfigurationCallback_hardwareEncodingChangedSwigExplicitConfigurationCallback(swigCPtr, this, arg0);
  }

  public void audioMeter(String arg0, float arg1) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_audioMeter(swigCPtr, this, arg0, arg1); else RingserviceJNI.ConfigurationCallback_audioMeterSwigExplicitConfigurationCallback(swigCPtr, this, arg0, arg1);
  }

  public void messageSend(String arg0) {
    if (getClass() == ConfigurationCallback.class) RingserviceJNI.ConfigurationCallback_messageSend(swigCPtr, this, arg0); else RingserviceJNI.ConfigurationCallback_messageSendSwigExplicitConfigurationCallback(swigCPtr, this, arg0);
  }

  public ConfigurationCallback() {
    this(RingserviceJNI.new_ConfigurationCallback(), true);
    RingserviceJNI.ConfigurationCallback_director_connect(this, swigCPtr, true, true);
  }

}
